name: flutter_map_markers
description: "Plugin for flutter_map to draw markers on map using canvas API with created presets."
version: 0.1.1
repository: https://github.com/ReinisSprogis/flutter_map_markers
issue_tracker: https://github.com/ReinisSprogis/flutter_map_markers/issues
funding:
  - https://github.com/sponsors/ReinisSprogis
  
topics:
  - flutter-map
  - map
  - markers
  - canvas

# This package should support all Flutter platforms. But tested only on windows/web/android so far.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  expandable_quadtree: ^0.1.1
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

screenshots:
  - description: 'This screenshot demonstrates the marker rendering on the map.'
    path: screenshots/asset_one.png
  - description: 'This screenshot demonstrates the marker rendering on the map.'
    path: screenshots/asset_two.png
