// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by SpriteSheetPacker for use with flutter_map_markers
// Source image: C:/Users/reini/Documents/assets/sprites/heli/fire/hdr/heli_fire.png



import 'package:flutter_map_markers/flutter_map_markers.dart';

class HeliFire {
  HeliFire._();

  static const List<SpriteInfo> sprites = [
    SpriteInfo(x: 0, y: 0, width: 54, height: 69), // ./h1_f1
    SpriteInfo(x: 56, y: 0, width: 54, height: 69), // ./h1_f2
    SpriteInfo(x: 0, y: 71, width: 54, height: 69), // ./h1_f3
    SpriteInfo(x: 56, y: 71, width: 54, height: 69), // ./h2_f1
    SpriteInfo(x: 112, y: 0, width: 54, height: 69), // ./h2_f2
    SpriteInfo(x: 112, y: 71, width: 54, height: 69), // ./h2_f3
    SpriteInfo(x: 168, y: 0, width: 54, height: 69), // ./h5
    SpriteInfo(x: 168, y: 71, width: 53, height: 69), // ./h6
  ];

  static SpriteInfo get h1_f1 => sprites[0];
  static SpriteInfo get h1_f2 => sprites[1];
  static SpriteInfo get h1_f3 => sprites[2];
  static SpriteInfo get h2_f1 => sprites[3];
  static SpriteInfo get h2_f2 => sprites[4];
  static SpriteInfo get h2_f3 => sprites[5];
  static SpriteInfo get h5 => sprites[6];
  static SpriteInfo get h6 => sprites[7];
}
