// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by SpriteSheetPacker


import 'package:flutter_map_markers/flutter_map_markers.dart';

class Heli8 {
  Heli8._();

  static const List<SpriteInfo> sprites = [
    SpriteInfo(x: 111, y: 71, width: 53, height: 68), // ./h1
    SpriteInfo(x: 166, y: 71, width: 53, height: 68), // ./h2
    SpriteInfo(x: 0, y: 0, width: 56, height: 69), // ./h3
    SpriteInfo(x: 171, y: 0, width: 51, height: 68), // ./h4
    SpriteInfo(x: 0, y: 71, width: 54, height: 69), // ./h5
    SpriteInfo(x: 56, y: 71, width: 53, height: 69), // ./h6
    SpriteInfo(x: 58, y: 0, width: 56, height: 69), // ./h7
    SpriteInfo(x: 116, y: 0, width: 53, height: 69), // ./h8
  ];

  static SpriteInfo get h1 => sprites[0];
  static SpriteInfo get h2 => sprites[1];
  static SpriteInfo get h3 => sprites[2];
  static SpriteInfo get h4 => sprites[3];
  static SpriteInfo get h5 => sprites[4];
  static SpriteInfo get h6 => sprites[5];
  static SpriteInfo get h7 => sprites[6];
  static SpriteInfo get h8 => sprites[7];
}
