// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by SpriteSheetPacker for use with flutter_map_markers
// Source image: C:/Users/reini/Documents/assets/sprites/diamon_marker/hdr/diamond_marker_anim.png



import 'package:flutter_map_markers/flutter_map_markers.dart';

class DiamondMarkerAnim {
  DiamondMarkerAnim._();

  static const List<SpriteInfo> sprites = [
    SpriteInfo(x: 2, y: 2, width: 23, height: 36,sourceWidth: 23, sourceHeight: 36,offsetX: 0, offsetY: 0), // ./f1
    SpriteInfo(x: 27, y: 2, width: 23, height: 36,sourceWidth: 23, sourceHeight: 36,offsetX: 0, offsetY: 0), // ./f2
    SpriteInfo(x: 2, y: 40, width: 23, height: 36,sourceWidth: 23, sourceHeight: 36,offsetX: 0, offsetY: 0), // ./f3
    SpriteInfo(x: 27, y: 40, width: 23, height: 36,sourceWidth: 23, sourceHeight: 36,offsetX: 0, offsetY: 0), // ./f4
    SpriteInfo(x: 52, y: 2, width: 23, height: 36,sourceWidth: 23, sourceHeight: 36,offsetX: 0, offsetY: 0), // ./f5
    SpriteInfo(x: 52, y: 40, width: 23, height: 36,sourceWidth: 23, sourceHeight: 36,offsetX: 0, offsetY: 0), // ./f6
    SpriteInfo(x: 2, y: 78, width: 23, height: 36,sourceWidth: 23, sourceHeight: 36,offsetX: 0, offsetY: 0), // ./f7
    SpriteInfo(x: 27, y: 78, width: 23, height: 36,sourceWidth: 23, sourceHeight: 36,offsetX: 0, offsetY: 0), // ./f8
    SpriteInfo(x: 52, y: 78, width: 23, height: 36,sourceWidth: 23, sourceHeight: 36,offsetX: 0, offsetY: 0), // ./f9
    SpriteInfo(x: 2, y: 2, width: 23, height: 36,sourceWidth: 23, sourceHeight: 36,offsetX: 0, offsetY: 0), // ./f10
  ];

  static SpriteInfo get f1 => sprites[0];
  static SpriteInfo get f10 => sprites[1];
  static SpriteInfo get f2 => sprites[2];
  static SpriteInfo get f3 => sprites[3];
  static SpriteInfo get f4 => sprites[4];
  static SpriteInfo get f5 => sprites[5];
  static SpriteInfo get f6 => sprites[6];
  static SpriteInfo get f7 => sprites[7];
  static SpriteInfo get f8 => sprites[8];
  static SpriteInfo get f9 => sprites[9];
}
