// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by SpriteSheetPacker for use with flutter_map_markers
// Source image: C:/Users/reini/Documents/assets/sprites/diamon_marker/hdr/gem_red_and_white.png

import 'package:flutter_map_markers/sprite_marker_layer/model/sprite_atlas.dart';

class GemRedAndWhite {
  GemRedAndWhite._();

  static const List<SpriteInfo> sprites = [
    SpriteInfo(x: 2, y: 2, width: 23, height: 35), // ./f1
    SpriteInfo(x: 27, y: 2, width: 23, height: 35), // ./f2
    SpriteInfo(x: 52, y: 2, width: 23, height: 35), // ./f3
    SpriteInfo(x: 77, y: 2, width: 23, height: 35), // ./f4
    SpriteInfo(x: 102, y: 2, width: 23, height: 35), // ./f5
    SpriteInfo(x: 127, y: 2, width: 23, height: 35), // ./f6
    SpriteInfo(x: 152, y: 2, width: 23, height: 35), // ./f7
    SpriteInfo(x: 177, y: 2, width: 23, height: 35), // ./f8
    SpriteInfo(x: 202, y: 2, width: 23, height: 35), // ./f9
    SpriteInfo(x: 2, y: 2, width: 23, height: 35), // ./f10

    SpriteInfo(x: 227, y: 2, width: 23, height: 35), // ./f1_red
    SpriteInfo(x: 252, y: 2, width: 23, height: 35), // ./f2_red
    SpriteInfo(x: 277, y: 2, width: 23, height: 35), // ./f3_red
    SpriteInfo(x: 302, y: 2, width: 23, height: 35), // ./f4_red
    SpriteInfo(x: 327, y: 2, width: 23, height: 35), // ./f5_red
    SpriteInfo(x: 352, y: 2, width: 23, height: 35), // ./f6_red
    SpriteInfo(x: 377, y: 2, width: 23, height: 35), // ./f7_red
    SpriteInfo(x: 402, y: 2, width: 23, height: 35), // ./f8_red
    SpriteInfo(x: 427, y: 2, width: 23, height: 35), // ./f9_red
    SpriteInfo(x: 227, y: 2, width: 23, height: 35), // ./f10_red
  ];

  static SpriteInfo get f1 => sprites[0];
  static SpriteInfo get f10 => sprites[1];
  static SpriteInfo get f10_red => sprites[2];
  static SpriteInfo get f1_red => sprites[3];
  static SpriteInfo get f2 => sprites[4];
  static SpriteInfo get f2_red => sprites[5];
  static SpriteInfo get f3 => sprites[6];
  static SpriteInfo get f3_red => sprites[7];
  static SpriteInfo get f4 => sprites[8];
  static SpriteInfo get f4_red => sprites[9];
  static SpriteInfo get f5 => sprites[10];
  static SpriteInfo get f5_red => sprites[11];
  static SpriteInfo get f6 => sprites[12];
  static SpriteInfo get f6_red => sprites[13];
  static SpriteInfo get f7 => sprites[14];
  static SpriteInfo get f7_red => sprites[15];
  static SpriteInfo get f8 => sprites[16];
  static SpriteInfo get f8_red => sprites[17];
  static SpriteInfo get f9 => sprites[18];
  static SpriteInfo get f9_red => sprites[19];
}
