// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by SpriteSheetPacker for use with flutter_map_markers
// Source image: C:/Users/reini/Documents/assets/sprites/gemstone/hdr/gemstone.png



import 'package:flutter_map_markers/sprite_marker_layer/model/sprite_atlas.dart';

class Gemstone {
  Gemstone._();

  static const List<SpriteInfo> sprites = [
    SpriteInfo(x: 140, y: 0, width: 32, height: 22), // ./gemstone0000
    SpriteInfo(x: 106, y: 56, width: 32, height: 25), // ./gemstone0001
    SpriteInfo(x: 72, y: 58, width: 32, height: 26), // ./gemstone0002
    SpriteInfo(x: 36, y: 56, width: 32, height: 27), // ./gemstone0003
    SpriteInfo(x: 72, y: 0, width: 32, height: 27), // ./gemstone0004
    SpriteInfo(x: 106, y: 0, width: 32, height: 26), // ./gemstone0005
    SpriteInfo(x: 72, y: 29, width: 32, height: 27), // ./gemstone0006
    SpriteInfo(x: 106, y: 28, width: 32, height: 26), // ./gemstone0007
    SpriteInfo(x: 106, y: 83, width: 32, height: 25), // ./gemstone0008
    SpriteInfo(x: 72, y: 86, width: 32, height: 26), // ./gemstone0009
    SpriteInfo(x: 72, y: 114, width: 32, height: 25), // ./gemstone0010
    SpriteInfo(x: 140, y: 24, width: 32, height: 22), // ./gemstone0011
    SpriteInfo(x: 140, y: 48, width: 32, height: 22), // ./gemstone0012
    SpriteInfo(x: 36, y: 138, width: 34, height: 22), // ./gemstone0013
    SpriteInfo(x: 106, y: 110, width: 34, height: 22), // ./gemstone0014
    SpriteInfo(x: 0, y: 113, width: 34, height: 24), // ./gemstone0015
    SpriteInfo(x: 36, y: 112, width: 34, height: 24), // ./gemstone0016
    SpriteInfo(x: 0, y: 86, width: 34, height: 25), // ./gemstone0017
    SpriteInfo(x: 36, y: 0, width: 34, height: 26), // ./gemstone0018
    SpriteInfo(x: 36, y: 85, width: 34, height: 25), // ./gemstone0019
    SpriteInfo(x: 36, y: 28, width: 34, height: 26), // ./gemstone0020
    SpriteInfo(x: 0, y: 0, width: 34, height: 27), // ./gemstone0021
    SpriteInfo(x: 0, y: 29, width: 34, height: 27), // ./gemstone0022
    SpriteInfo(x: 0, y: 58, width: 34, height: 26), // ./gemstone0023
    SpriteInfo(x: 106, y: 134, width: 34, height: 22), // ./gemstone0024
  ];

  static SpriteInfo get gemstone0000 => sprites[0];
  static SpriteInfo get gemstone0001 => sprites[1];
  static SpriteInfo get gemstone0002 => sprites[2];
  static SpriteInfo get gemstone0003 => sprites[3];
  static SpriteInfo get gemstone0004 => sprites[4];
  static SpriteInfo get gemstone0005 => sprites[5];
  static SpriteInfo get gemstone0006 => sprites[6];
  static SpriteInfo get gemstone0007 => sprites[7];
  static SpriteInfo get gemstone0008 => sprites[8];
  static SpriteInfo get gemstone0009 => sprites[9];
  static SpriteInfo get gemstone0010 => sprites[10];
  static SpriteInfo get gemstone0011 => sprites[11];
  static SpriteInfo get gemstone0012 => sprites[12];
  static SpriteInfo get gemstone0013 => sprites[13];
  static SpriteInfo get gemstone0014 => sprites[14];
  static SpriteInfo get gemstone0015 => sprites[15];
  static SpriteInfo get gemstone0016 => sprites[16];
  static SpriteInfo get gemstone0017 => sprites[17];
  static SpriteInfo get gemstone0018 => sprites[18];
  static SpriteInfo get gemstone0019 => sprites[19];
  static SpriteInfo get gemstone0020 => sprites[20];
  static SpriteInfo get gemstone0021 => sprites[21];
  static SpriteInfo get gemstone0022 => sprites[22];
  static SpriteInfo get gemstone0023 => sprites[23];
  static SpriteInfo get gemstone0024 => sprites[24];
}
