// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by SpriteSheetPacker for use with flutter_map_markers
// Source image: C:/Users/reini/Documents/assets/sprites/heli/heli_2/hdr/heli_2.png


import 'package:flutter_map_markers/flutter_map_markers.dart';

class Heli2 {
  Heli2._();

  static const List<SpriteInfo> sprites = [
    SpriteInfo(x: 0, y: 0, width: 54, height: 69,sourceWidth: 54, sourceHeight: 69,offsetX: 0, offsetY: 0), // ./h5
    SpriteInfo(x: 56, y: 0, width: 53, height: 69,sourceWidth: 53, sourceHeight: 69,offsetX: 0, offsetY: 0), // ./h6
  ];

  static SpriteInfo get h5 => sprites[0];
  static SpriteInfo get h6 => sprites[1];
}
