// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by SpriteSheetPacker for use with flutter_map_markers
// Source image: C:/Users/reini/Documents/assets/sprites/puff/64_64/packed/hdr/puffy_gems.png



import 'package:flutter_map_markers/sprite_marker_layer/model/sprite_atlas.dart';

class PuffyGems {
  PuffyGems._();

  static const List<SpriteInfo> sprites = [
    SpriteInfo(x: 0, y: 0, width: 64, height: 64), // ./0
    SpriteInfo(x: 66, y: 0, width: 64, height: 64), // ./1
    SpriteInfo(x: 0, y: 66, width: 64, height: 64), // ./2
    SpriteInfo(x: 66, y: 66, width: 64, height: 64), // ./3
   // SpriteInfo(x: 132, y: 0, width: 64, height: 64), // ./4
    SpriteInfo(x: 0, y: 132, width: 64, height: 64), // ./5
    SpriteInfo(x: 66, y: 132, width: 64, height: 64), // ./6
    SpriteInfo(x: 132, y: 66, width: 64, height: 64), // ./7
    SpriteInfo(x: 132, y: 132, width: 64, height: 64), // ./8
    SpriteInfo(x: 198, y: 0, width: 64, height: 64), // ./9
    SpriteInfo(x: 0, y: 198, width: 64, height: 64), // ./10
    SpriteInfo(x: 66, y: 198, width: 48, height: 48), // ./gemstone0000
    SpriteInfo(x: 198, y: 66, width: 48, height: 48), // ./gemstone0001
    SpriteInfo(x: 116, y: 198, width: 48, height: 48), // ./gemstone0002
    SpriteInfo(x: 198, y: 116, width: 48, height: 48), // ./gemstone0003
    SpriteInfo(x: 248, y: 66, width: 48, height: 48), // ./gemstone0004
    SpriteInfo(x: 66, y: 248, width: 48, height: 48), // ./gemstone0005
    SpriteInfo(x: 166, y: 198, width: 48, height: 48), // ./gemstone0006
    SpriteInfo(x: 264, y: 0, width: 48, height: 48), // ./gemstone0007
    SpriteInfo(x: 0, y: 264, width: 48, height: 48), // ./gemstone0008
    SpriteInfo(x: 116, y: 248, width: 48, height: 48), // ./gemstone0009
    SpriteInfo(x: 248, y: 116, width: 48, height: 48), // ./gemstone0010
    SpriteInfo(x: 216, y: 198, width: 48, height: 48), // ./gemstone0011
    SpriteInfo(x: 166, y: 248, width: 48, height: 48), // ./gemstone0012
    SpriteInfo(x: 298, y: 66, width: 48, height: 48), // ./gemstone0013
    SpriteInfo(x: 66, y: 298, width: 48, height: 48), // ./gemstone0014
    SpriteInfo(x: 314, y: 0, width: 48, height: 48), // ./gemstone0015
    SpriteInfo(x: 116, y: 298, width: 48, height: 48), // ./gemstone0016
    SpriteInfo(x: 298, y: 116, width: 48, height: 48), // ./gemstone0017
    SpriteInfo(x: 216, y: 248, width: 48, height: 48), // ./gemstone0018
    SpriteInfo(x: 266, y: 198, width: 48, height: 48), // ./gemstone0019
    SpriteInfo(x: 166, y: 298, width: 48, height: 48), // ./gemstone0020
    SpriteInfo(x: 266, y: 248, width: 48, height: 48), // ./gemstone0021
    SpriteInfo(x: 216, y: 298, width: 48, height: 48), // ./gemstone0022
    SpriteInfo(x: 316, y: 198, width: 48, height: 48), // ./gemstone0023
    SpriteInfo(x: 266, y: 298, width: 48, height: 48), // ./gemstone0024
  ];

  static SpriteInfo get _0 => sprites[0];
  static SpriteInfo get _1 => sprites[1];
  static SpriteInfo get _10 => sprites[2];
  static SpriteInfo get _2 => sprites[3];
  static SpriteInfo get _3 => sprites[4];
  static SpriteInfo get _4 => sprites[5];
  static SpriteInfo get _5 => sprites[6];
  static SpriteInfo get _6 => sprites[7];
  static SpriteInfo get _7 => sprites[8];
  static SpriteInfo get _8 => sprites[9];
  static SpriteInfo get _9 => sprites[10];
  static SpriteInfo get gemstone0000 => sprites[11];
  static SpriteInfo get gemstone0001 => sprites[12];
  static SpriteInfo get gemstone0002 => sprites[13];
  static SpriteInfo get gemstone0003 => sprites[14];
  static SpriteInfo get gemstone0004 => sprites[15];
  static SpriteInfo get gemstone0005 => sprites[16];
  static SpriteInfo get gemstone0006 => sprites[17];
  static SpriteInfo get gemstone0007 => sprites[18];
  static SpriteInfo get gemstone0008 => sprites[19];
  static SpriteInfo get gemstone0009 => sprites[20];
  static SpriteInfo get gemstone0010 => sprites[21];
  static SpriteInfo get gemstone0011 => sprites[22];
  static SpriteInfo get gemstone0012 => sprites[23];
  static SpriteInfo get gemstone0013 => sprites[24];
  static SpriteInfo get gemstone0014 => sprites[25];
  static SpriteInfo get gemstone0015 => sprites[26];
  static SpriteInfo get gemstone0016 => sprites[27];
  static SpriteInfo get gemstone0017 => sprites[28];
  static SpriteInfo get gemstone0018 => sprites[29];
  static SpriteInfo get gemstone0019 => sprites[30];
  static SpriteInfo get gemstone0020 => sprites[31];
  static SpriteInfo get gemstone0021 => sprites[32];
  static SpriteInfo get gemstone0022 => sprites[33];
  static SpriteInfo get gemstone0023 => sprites[34];
  static SpriteInfo get gemstone0024 => sprites[35];
}
